{% set name = "types-boto" %}
{% set version = "2.49.18.20240806" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-boto-{{ version }}.tar.gz
  sha256: 31ccb4a618e413ab2e5960376c7161279e6ede52bf81f8a67abb222f01439b7c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - types-six

test:
  commands:
    - test -f $SP_DIR/boto-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for boto
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
